GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Brananti Ratuasty",
    "email": "brananti@gmail.com",
    "gender": "Female"
}

###
PATCH http://localhost:3000/users/8
Content-Type: application/json

{
    "name": "Destio"
}

###
DELETE http://localhost:3000/users/7
